apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: devops-api
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "postgres"
  DATABASE_NAME: "devops_task"
