apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service  # matches frontend proxy (minor, no front-end yet)
                port:
                  number: 80
