
apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
spec:
  selector:
    application: devops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # might be required by cloud provider for external traffic
